# Laboratorium 

In [ ]:
import numpy as np

#### Zadanie 1
Napisz metodę, która oblicza pole między osią OX a wykresem funkcji na danym przedziale za pomocą sum Riemanna (przybliżeń prostokątami). Sprawdź jej działanie na wybranej przez siebie funkcji porównując z wynikiem całkownia symbolicznego. 

Korzystając z symbolicznych pochodnych i szukania ekstremów dobierz takie parametry do swojej funkcji, aby błąd całkowania był mniejszy niż $10^{-5}$.


In [ ]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [33]:
def calka(funkcja,a,b,N):
  podzial=np.linspace(a,b,N)
  podstawa=(b-a)/(N-1)
  wartosc=0
  for i in range(N-1):
    wartosc+=podstawa*abs(funkcja(podzial[i]))
  return wartosc


In [ ]:
calka(lambda x:x**2,0,1,1000)

0.33283299983333353

In [35]:
calka(lambda x:-x**2*3*x+sin(x),0,1,1000)

0.44720455034241857

In [25]:
from math import *
from sympy import *
x=symbols('x')
f=-x**2*3*x+sin(x)
f1=f.diff(x)
f1

-9*x**2 + cos(x)

In [26]:
f2=f1.diff(x)
f2

-18*x - sin(x)

In [27]:
f3=f2.diff(x)
f3


-cos(x) - 18

In [42]:
10**5*3/np.sqrt(4)


150000.0

In [43]:
calka(lambda x:-x**2*3*x+sin(x),0,1,150000)


0.4482769399213344

#### Zadanie 2
a) Zaimplementuj w postaci funkcji algorytm obliczania pierwiastka kwadratowego z $x>0$ z wykorzystaniem algorytmu Herona. Funkcja powinna przyjmować jako argumenty liczby: $x$, punkt startowy $x_0$ oraz liczbę kroków (wyrazów ciągu do obliczenia).

b) Następnie, dodaj argument show_step (domyślnie ustawiony jako False), który będzie pozwalał wyświetlać kolejne kroki przybliżenia aż do zadanego.

c) Na bazie a) stwórz nową funkcję, która wykona odpowiednią liczbę kroków by przybliżenie miało podaną dokładność

# NumPy

np.ndarray (N-dimensional array)

Najważniejsze atrybuty:
* shape
* ndim
* size
* dtype (int,float,bool,complex)
* nbytes


In [ ]:
tab=np.array([[1,2],[3,4],[4,1]])

In [ ]:
tab.nbytes

48

#### Zadanie 3

Stwórz dowolną tablicę liczb całkowitych ndarray z zagnieżdżonej listy. Sprawdź jej różne atrybuty. Spróbuj zamienić wszystkie liczby całkowite na zmiennoprzecinkowe.

In [ ]:
tab2=np.array(tab,dtype=float)

In [ ]:
tab2

array([[1., 2.],
       [3., 4.],
       [4., 1.]])

In [ ]:
tab3=np.array([-1,0,1])

In [ ]:
np.sqrt(tab3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([nan,  0.,  1.])

In [ ]:
tab4=tab3.astype(complex)
tab4
np.sqrt(tab4).imag

array([1., 0., 0.])

### Konstruktory:
* np.array - tworzy z różnych tablicopodobnych typów
* np.zeros - same zera
* np.ones - same jedynki
* np.eye - macierz identycznościowa
* np.diag - macierz z elementami na przekątnej

* **!** np.linspace(start,koniec (domknięty),liczba elementów)
* **!** np.arange(start,koniec (otwarty),krok)
* np.meshgrid - tworzy siatkę punktów z pojedynczych wektorów) - zwraca tablice poszczególnych współrzędnych

from scipy.linalg import block_diag

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.meshgrid([1,2,3],['a','b','c'])

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), array([['a', 'a', 'a'],
        ['b', 'b', 'b'],
        ['c', 'c', 'c']], dtype='<U1')]

#### Zadanie 4
Skonstruuj macierz:
$$
Mat1=\begin{bmatrix}
1 &1 &0&0&0&0&0\\
1&1&0&0&0&0&0\\
0&0&0&0&0&0&0 \\
0&0&0&0&0&0&0 \\
0&0&0&0&3&0&0 \\
0&0&0&0&0&2&4 \\
0&0&0&0&0&4&2 \\
\end{bmatrix}
$$

In [ ]:
from scipy.linalg import block_diag
Mat1=block_diag(np.ones((2,2)),np.zeros((2,2)),3,(4*np.ones((2,2))-2*np.eye(2)))
Mat1

array([[1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0., 2., 4.],
       [0., 0., 0., 0., 0., 4., 2.]])

In [ ]:
Mat1[0,0]=3

In [ ]:
Mat1

array([[3., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0., 2., 4.],
       [0., 0., 0., 0., 0., 4., 2.]])

In [ ]:
Mat1[:,::-1]

array([[0., 0., 0., 0., 0., 1., 3.],
       [0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0.],
       [4., 2., 0., 0., 0., 0., 0.],
       [2., 4., 0., 0., 0., 0., 0.]])

#### Zadanie 5
W macierzy Mat1 zamień miejscami lewy górny narożnik 4X4 z prawym dolnym 3x3 (nazwij wynik Mat2)

#### Zadanie 6
Stwórz macierz Mat3, która będzie zawierała tylko elementy z Mat2 o obu parzystych współrzędnych.

In [ ]:
Mat1[:4,:4]

array([[3., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
Mat1[-3:,-3:]

array([[3., 0., 0.],
       [0., 2., 4.],
       [0., 4., 2.]])

In [ ]:
Mat2=block_diag(Mat1[-3:,-3:],Mat1[:4,:4])

In [ ]:
Mat3=Mat2[1::2,1::2]

### Zadanie 7
Utwórz tablicę

$$
\begin{bmatrix}
1&2&3&4\\
5&6&7&8 \\
9&10&11&12\\
13&14&15&16
\end{bmatrix}
$$

Inne przydatne funkcje:

* łączenie macierzy ```np.concatenate((tab1,tab2),argumenty)```
* rozdzielanie macierzy ```np.array_split(tab1, \<liczba czesci\>)```
* wybieranie indeksów spełniających logiczny warunek: ```np.where(tab1>0)```
* sortowanie ```np.sort(tab1)```